### ISSUE TITLE
Polkadot release v0.9.38

### ISSUE THREAD

**Issue by masapr** [scs/substrate-api-client#469]
Update to new polkadot branch v0.9.38

- [x] `master` branch: set new polkadot master in `Cargo.toml`: #462 
- [x] create new branch `polkadot-v0.9.38`: based on tag `v0.9.0`: #468 
- [x] create new branch `polkadot-v0.9.38-tag-v0.10.0`: based on tag `v0.10.0`: #467  
- [x] create new branch `polkadot-v0.9.38-tag-v0.7.0`: based on tag `v0.7.0`: #466

**Comment by haerdib** [comment]
I think that one is finished, is it not?

**Comment by masapr** [comment]
yes, it is
